### ISSUE TITLE
Tests implementieren

### ISSUE THREAD

**Issue by RedTo** [ob-algdatii-ss18/leistungsnachweis-algo#3]
Tests mit Google-Tests implementieren und von Travis ausführen lassen

**Comment by RedTo** [comment]
Google Tests ist implementiert und die ersten Tests sind auch schon umgesetzt. Nur bekomme ich es nicht auf die Reihe eine eigene Methode zu machen die zum Beispiel die 0en zählt. Momentan ist die in jedem Test eingebaut.

@AndiAndreas und @keller-c weiß jemand wie ich einen TestHelper bauen kann, also eine Klasse bei der ich statische Methoden drin hab und die dann in den Tests aufrufen kann?

**Comment by keller-c** [comment]
@RedTo ich habe dein Problem gelöst. Ein anonymer namespace hat geholfen. Allerdings schlagen hin und wieder Tests fehl.

**Comment by RedTo** [comment]
Wir brauchen auch noch eine Möglichkeit um die Zahlen einer Spalte bzw einer Zeile (und Diagonale) zu überprüfen. Mein Grundgedanke war etwas wie ein Set, weil man sich da ja sicher sein kann, dass jede Zahl nur 1x drin vor kommt. Aber bisher bin ich da noch nicht dahinter gekommen, werde es aber weiter versuchen...

**Comment by RedTo** [comment]
Tests sind soweit auf dem aktuellen Stand. Sobald Erweiterungen eingefügt werden, müssen allerdings dafür natürlich auch Tests erstellt werden.
