### ISSUE TITLE
Doxygen einbauen

### ISSUE THREAD

**Issue by RedTo** [ob-algdatii-ss18/leistungsnachweis-algo#6]
Doxygen einbauen und von Travis generieren lassen

**Comment by keller-c** [comment]
Doxyfile enthält doxygen Konfiguration. @RedTo ich bräuchte noch die Travis Seite um eventuell daran was anzupassen. Im Zuge dessen sollten wir auch ein wiki erstellen mit allgemeineren Infos?

**Comment by RedTo** [comment]
@keller-c Travis musst du bei dir selbst einrichten. Du musst Travis mit deinem Github-Konto verbinden um dann auf die Repositories zugreifen zu können.

Einstellungen von Travis werden in der Datei [.travis.yml](https://github.com/ob-algdatii-ss18/leistungsnachweis-algo/blob/master/.travis.yml) gemacht, die liegt ganz normal im Git-Verzeichnis.

**Comment by keller-c** [comment]
@RedTo Okay. Dane werd ich machen. Ich dachte nur es gibt ein Travis für das Projekt und nicht für jeden Projektteilnehmer.

**Comment by RedTo** [comment]
Travis baut doxygen schon erfolgreich.
