### ISSUE TITLE
Mögliche Erweiterung: Teilsummen

### ISSUE THREAD

**Issue by RedTo** [ob-algdatii-ss18/leistungsnachweis-algo#8]
Ausgefülltes Sudoku in Teilbereiche mit Teilsummen unterteilen, erst dann Zahlen löschen.

**Comment by RedTo** [comment]
Hierfür muss ein Algorithmus gefunden werden um zufällige Teilsummen zu bilden und diese entsprechend zu visualisieren. (Kleine Abgrenzungen einzeichnen + Teilsumme, oben links? reinschreiben)

**Comment by RedTo** [comment]
@keller-c und @AndiAndreas was meint ihr? Sollen wir dieses Feature weg lassen?

**Comment by keller-c** [comment]
ich würde es weglassen. Können mit ihm aber nochmal reden und fragen ob das für die Abgabe reicht?

**Comment by RedTo** [comment]
Ich denke wenn wir das Lösen noch einbauen und vielleicht auch die BigSudokus (optional X-Sudokus) dann sollte das reichen.

Bei den BigSudokus ist ja eh nur die Kunst, dass man die Zahlen reinschreibt und der Algorithmus die dann nicht verändert. Dann generiert man 1 Sudoku, setzt die vier Quads jeweils in ein neues ein und generiert die auch. Die fünf müssen halt dann noch entsprechend visuell dargestellt werden und fertig ist die Sache...

Bei den X-Sudokus müsste man halt noch die Diagonalen mit in die Nachbarschaftsbeziehung aufnehmen und auch noch entsprechend das X dann visuallisieren.

Aber ich denke das ist ausreichend für die Abgabe.
